import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import Transaction from 'src/database/models/transaction.model';
import axios from 'axios';

@Injectable()
export class TaskService {
  @Cron('0 * * * * *')
  public pullAndResolveRepeatableTransactions() {
    Logger.log('Called when the current second every 1 minute ', 'TaskService');
  }

  @Cron('0 */5 * * * *')
  public async pushRepeatableTransactions() {
    const transactions = await Transaction.query().where({
      isTemplate: true,
      isAutoGenerated: false,
    });

    Logger.log(
      'Called when the current second every 5 minute ' +
      ' ' +
      JSON.stringify(transactions),
      'TaskService',
    );
  }

  @Cron('0 */15 * * * *')
  public async refreshHeroku() {
    Logger.log('Refresh heroku', 'App');

    await axios.get('https://mymoney-server-api.herokuapp.com/');
  }
}
