import { Model } from 'objection';
import UserCategory from './user-category.model';
import Currency from './currency.model';
import { TransactionType } from 'src/transactions/transaction-type';

export interface TransactionScheduleTemplate {
  interval: 'day' | 'week' | 'month' | 'year';
  intervalOptions?: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] | 'all';
  frequency: number;
}

export const categoryInId = '4ade3988-43f4-4ab5-951a-223806c9f5c7';
export const categoryOutId = '981fd55b-2840-4d9d-a758-f24e4bce1176';
export const categoryTransferId = 'bec3812e-5eb6-495f-b021-58bc39184cc7';
export class Transaction extends Model {
  public id: string;
  public userId: number;
  public type: TransactionType;
  public categoryId: string;
  public sourceWalletId: string;
  public destinationWalletId: string;
  public currencyId: string;
  public description: string;
  public fine: number;
  public amount: number;
  public isTemplate: boolean;
  public isPlanned: boolean;
  public isAutoGenerated: boolean;
  public isImported: boolean;
  public isNecessary: boolean;
  public meta: any;
  public template?: TransactionScheduleTemplate;
  public date: Date;
  public syncAt: Date;
  public createdAt: Date;
  public updatedAt: Date;
  public deletedAt: Date;
  public currency: Currency;
  public category: UserCategory;

  static get tableName() {
    return 'transactions';
  }

  static get relationMappings() {
    return {
      currency: {
        relation: Model.HasOneRelation,
        modelClass: Currency,
        join: {
          from: 'transactions.currencyId',
          to: 'currencies.id',
        },
      },
      category: {
        relation: Model.HasOneRelation,
        modelClass: UserCategory,
        join: {
          from: 'transactions.categoryId',
          to: 'user_categories.id',
        },
      },
    };
  }
}

export default Transaction;
