name: Deploy

on:
  push:
    branches:
      - master

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'mymoney-server-api'
          heroku_email: 'kabalx47@gmail.com'
          usedocker: true
          appdir: 'api'
      - run: heroku run yarn migrate
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'mymoney-accounting'
          heroku_email: 'kabalx47@gmail.com'
          usedocker: true
          appdir: 'dashboard'
          docker_build_args: |
            NODE_ENV
            SKIP_PREFLIGHT_CHECK
            REACT_APP_SERVER
            REACT_APP_GOOGLE_CLIENT_ID
        env:
          REACT_APP_SERVER: 'https://mymoney-server-api.herokuapp.com/'
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          SKIP_PREFLIGHT_CHECK: 'true'
          NODE_ENV: 'production'
