name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'mymoney-server-api'
          heroku_email: 'kabalx47@gmail.com'
          usedocker: true
        env:
          REACT_APP_SERVER: 'https://mymoney-server-api.herokuapp.com/'
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          HD_VERSION: ${{ github.sha }}
      - run: heroku run yarn migrate
